### ISSUE TITLE
Can you provide a wiring diagram?

### ISSUE THREAD

**Issue by NeoMod** [emc2cube/MyWeatherGatewayESP8266#1]
Thank you very much for this precious info!

I was struggling figuring out how to - and if it was possible - have a BME280 sensor and a NRF24 radio coexisting on a little NodeMCU while using MySensors Library.

Your sketch was highly documented and commented, thank you so much.

My only doubt is about lines 101-103: in the presentation you said "Because of the default wiring of the radio, you will need either to move the CE pin, or to customize wich ports will be used as I2C bus." 

Only one action is required, right? To be sure: deciding to move the CE pin and leaving default I2C on D2 and D3 is a viable solution?

Thank you for your time and your attention.

**Comment by emc2cube** [comment]
Yes this is a viable solution. Check your board definition in variants/nodemcu/pins_arduino.h to see which pins are the defaults I2C gpio for your board and comment the lines 102 and 103, or update them the GPIO you are using here.

Dont forget to uncomment line 38 and declare the pin you are now using for CE.

In doubt you can define CE, SDA and SCL all-together.
